version: "3.2"
services:
  redis:
    image: "redis:alpine"
    command: redis-server
#    --requirepass sOmE_sEcUrE_pAsS
    ports:
    - "6379:6379"
    volumes:
    - $PWD/redis-data:/var/lib/redis
    - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
    - REDIS_REPLICATION_MODE=master
  cassandra:
    image: cassandra:latest
    container_name: cassandra
    restart: always
    ports:
    - "9042:9042"
    volumes:
      - ./out/cassandra_data:/var/lib/cassandra

