spring:
  profiles:
    active: test
  redis:
    host: localhost
    port: 6379
  data:
    cassandra:
      contact-points: localhost
#     todo: 테스트용 임베디드 카산드라를 쓸 때 9142로 바꾸는게 좋을 듯
      port: 9142
      keyspace-name: testKeySpace
      local-datacenter: datacenter1
