--  todo: region 서비스를 만들고 나면, 이벤트를 컨슘하여 초기 데이터 설정하는 방식으로 수정.
INSERT INTO chat_room (name, room_id) VALUES ('WANGSIMNI', 110841e3-e6fb-4191-8fd8-5674a5107c33) IF NOT EXISTS;
INSERT INTO chat_room (name, room_id) VALUES ('CAMPUS', 4f0a4a02-26c6-4441-915d-c0f61cda0178) IF NOT EXISTS;
INSERT INTO chat_room (name, room_id) VALUES ('DORMITORY', cd865f7d-3923-4065-a5e6-5c093e7b5442) IF NOT EXISTS;
INSERT INTO chat_room (name, room_id) VALUES ('ITAEWON', 56645394-80e0-4fb3-a2ad-097832e39233) IF NOT EXISTS;
