# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    name: setup
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
      #      - uses: lukka/set-shell-env@v1
      #        name: setup shell variables
      #        with:
      #          args: NEW_VAR_NAME='haha'
      #          NEW_VAR_NAME: new_var_value
      #          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #          EXAMPLE: hahahaha
      - name: Bump version and push tag
        #        todo: 왜 sudo가 필요하지..?
        run: export BUILD_NAME=haha
          |  chmod +x ./src/main/resources/scripts/tag_build.sh
          | sudo sh ./src/main/resources/scripts/tag_build.sh
        env:
          TAG_NAME: haha
#        run: echo $GITHUB_TOKENT
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          BUILD_NAME: chat-${{github.ref}}
#          REPO_OWNER: beyond-eyesight
#          RELEASE_BRANCHES: develop
#      - name: Set up JDK 1.8
#        uses: actions/setup-java@v1
#        with:
#          java-version: 1.8
#
#      - name: Grant execute permission for gradlew
#        run: chmod +x gradlew
#      - name: Build with Gradle
#        run: ./gradlew build
#      - name: install ecs-cli
#        uses: marocchino/setup-ecs-cli@v1
#        with:
#          version: "v1.18.0"


#    - name: Create a GitHub release
#      uses: actions/create-release@v1
#      env:
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#      with:
#        tag_name: ${{ steps.tag_version.outputs.new_tag }}
#        release_name: Release ${{ steps.tag_version.outputs.new_tag }}
#        body: ${{ steps.tag_version.outputs.changelog }}


