# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ main, release/* ]
  pull_request:
    branches: [ main, release/* ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: bump version
      id: tag_version
      uses: anothrNick/github-tag-action@1.26.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        RELEASE_BRANCHES: main, release.*
    - name: tag release
      uses: ./.github/workflows/actions/tag_release
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BUILD_NAME: ${{ steps.tag_version.outputs.new_tag }}
        GITHUB_REPOSITORY: $GITHUB_REPOSITORY
        GITHUB_API_URL: $GITHUB_API_URL
        GITHUB_TARGET_BRANCH: main
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
